#ifndef FINAL_LAYER_NORM_ACTIVATION_ACT_SCALING_FACTOR_H
#define FINAL_LAYER_NORM_ACTIVATION_ACT_SCALING_FACTOR_H

const float final_layer_norm_activation_act_scaling_factor[1] = {0.0};

#endif // FINAL_LAYER_NORM_ACTIVATION_ACT_SCALING_FACTOR_H
