#ifndef SELF_ATTN_SOFTMAX_ACT_ACT_SCALING_FACTOR_H
#define SELF_ATTN_SOFTMAX_ACT_ACT_SCALING_FACTOR_H

const float self_attn_softmax_act_act_scaling_factor[1] = {63360856000.0};

#endif // SELF_ATTN_SOFTMAX_ACT_ACT_SCALING_FACTOR_H
