// cat_done.v

// Generated using ACDS version 21.1 169

`timescale 1 ps / 1 ps
module cat_done (
		output wire  out_conduit,  //  out_conduit.conduit
		input  wire  in_conduit_0  // in_conduit_0.conduit
	);

	cat_done_avalon_concatenate_singlebit_conduits_10_bjzeuhq cat_done (
		.out_conduit  (out_conduit),  //  output,  width = 1,  out_conduit.conduit
		.in_conduit_0 (in_conduit_0)  //   input,  width = 1, in_conduit_0.conduit
	);

endmodule
