:: This batch file will compile the example design:
::   1) default      Compile the example design
::   2) clean        Remove any temporary files generated by the compiler
:: Usage: build.bat <target>
:: Example: build.bat default

@ECHO OFF
setlocal ENABLEDELAYEDEXPANSION
:: Only 2 arguments expected
if not "%3"=="" goto usage

set "TARGET=default"
if not "%1"=="" set "TARGET=%1"

set "DEVICE=Cyclone10GX"
if not "%2"=="" set "DEVICE=%2"

set "CXX=i++"
set "FILENAME=testbench"
set "FILENAME2=testbench_cosim"
set "LFLAGS=-o build/%FILENAME%.exe"
set "LFLAGS2=-o build/%FILENAME2%.exe"
set "SRCFILES=testbench.cpp"
set "INCLUDE="

if "%TARGET%" == "default" (  
  echo %CXX% -march=x86-64 %INCLUDE% %SRCFILES% %LFLAGS%
  %CXX% -march=x86-64 %INCLUDE% %SRCFILES% %LFLAGS%

  if not %errorlevel% == 0 (
    echo Error: Compile failed
    exit /b 1
  )

  echo %CXX% -march=%DEVICE% %INCLUDE% %SRCFILES% %LFLAGS2%
  %CXX% -march=%DEVICE% %INCLUDE% %SRCFILES% %LFLAGS2%

  if not %errorlevel% == 0 (
    echo Error: Compile failed
    exit /b 1
  )

  cd build
  echo %FILENAME%.exe
  %FILENAME%.exe
  echo %FILENAME2%.exe
  %FILENAME2%.exe
  goto:eof

) 
else if "%TARGET%" == "clean" (
  del /s /f /q *.tmp
  del /s /f /q *.exe
  del /s /f /q *.obj
  rmdir /s /q tutorial-fpga.prj 2>nul
  goto:eof
  ) 
else (
  goto usage
)

:: Dump the usage if we get unexpected input
:usage
echo Usage: build.bat [target]
echo Targets: default, clean
echo Example: build.bat default
exit /b 2
