// clock_reset.v

// Generated using ACDS version 21.1 169

`timescale 1 ps / 1 ps
module clock_reset #(
		parameter RESET_CYCLE_HOLD = 4
	) (
		output wire  clock,         //      clock.clk
		output wire  resetn,        //      reset.reset_n
		output wire  clock2x,       //    clock2x.clk
		input  wire  trigger_reset  // reset_ctrl.conduit
	);

	hls_sim_clock_reset #(
		.RESET_CYCLE_HOLD (RESET_CYCLE_HOLD)
	) clock_reset (
		.clock         (clock),         //  output,  width = 1,      clock.clk
		.resetn        (resetn),        //  output,  width = 1,      reset.reset_n
		.clock2x       (clock2x),       //  output,  width = 1,    clock2x.clk
		.trigger_reset (trigger_reset)  //   input,  width = 1, reset_ctrl.conduit
	);

endmodule
